import { useState, type FormEvent } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, CheckCircle2, Clock3, Heart, MapPin, ShoppingBag, Truck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useBakery } from '@/components/bakery-shell';
import { CakeCards, PageIntro } from '@/components/bakery-content';
import { cakes, rupiah, getJakartaMinutes } from '@/lib/bakery';
import customImage from '@/assets/custom-cakes.jpg';
import storyImage from '@/assets/hero-bread.jpg';

function todayJakarta() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function tomorrow() { const date = new Date(`${todayJakarta()}T12:00:00+07:00`); date.setDate(date.getDate() + 1); return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(date); }
export function CustomPage() {
 const { addItem } = useBakery(); const [cakeId, setCakeId] = useState(cakes[0].id); const [date, setDate] = useState(''); const [size, setSize] = useState('16 cm'); const [message, setMessage] = useState(''); const [note, setNote] = useState(''); const [added, setAdded] = useState(false);
 const selected = cakes.find(cake => cake.id === cakeId) ?? cakes[0]; const price = (selected?.price ?? 0) + (size === '20 cm' ? 75000 : 0);
 function submit(e: FormEvent) { e.preventDefault(); if (!selected) return; if (!date || date < tomorrow()) { setMessage('Pilih tanggal paling cepat besok, ya.'); return; } addItem({ id: `custom-${selected.id}-${size}-${date}-${note}`, name: `${selected.name} (${size})`, price, image: selected.image, custom: true, note: `Untuk ${date}${note ? ` · ${note}` : ''}` }); setMessage('Kue sudah masuk keranjang. Desain akhir dan DP akan dibicarakan lewat WhatsApp.'); setAdded(true); }
 if (!selected) return null;
 return <><PageIntro label="DIBUAT KHUSUS BUAT KAMU" title="Kue yang terasa personal." description="Pilih rasa dan ceritakan idemu. Kami buat mockup desain dulu, jadi hasil akhirnya nggak bikin deg-degan."/><div className="container page-content"><div className="info-strip"><Clock3 size={20}/> Pesan paling lambat H-1 · DP 50% setelah desain disepakati · Desain di-mockup dulu via WhatsApp</div><CakeCards/><div className="custom-layout" style={{ marginTop: 58 }}><div className="custom-form"><h2>Mulai pesanan kuemu</h2><form onSubmit={submit}><div className="form-grid"><label className="form-field">Pilih kue<select value={cakeId} onChange={e => { setCakeId(e.target.value); setAdded(false); }}>{cakes.map(cake => <option key={cake.id} value={cake.id}>{cake.name}</option>)}</select></label><label className="form-field">Ukuran<select value={size} onChange={e => setSize(e.target.value)}><option>16 cm</option><option>20 cm</option></select></label><label className="form-field">Tanggal dibutuhkan<input type="date" min={tomorrow()} value={date} onChange={e => setDate(e.target.value)} required/></label><label className="form-field">Nama kamu<input type="text" placeholder="Nama pemesan" required/></label><label className="form-field full">Ide desain / tulisan di kue<textarea placeholder="Misalnya: warna pastel, tulisan Selamat Ulang Tahun Ara..." value={note} onChange={e => setNote(e.target.value)} /></label></div><p className="form-hint">Harga mulai {rupiah(price)}. Belum ada pembayaran di demo ini; DP 50% baru setelah mockup disetujui.</p><Button type="submit" size="lg">Tambahkan ke Keranjang <ArrowRight size={16}/></Button>{message && <div className="form-success" role="status">{message} {added && <Link to="/keranjang" className="text-link">Lihat keranjang →</Link>}</div>}</form></div><aside className="custom-aside"><img src={customImage} alt="Tiga contoh kue ulang tahun buatan FIDA'S" width={1500} height={1000}/><h3>Gampang, dari ide jadi kue.</h3><ol><li>Pilih rasa, ukuran, dan tanggal.</li><li>Ceritakan desain yang kamu mau.</li><li>Sepakati mockup & DP 50% via WhatsApp.</li><li>Ambil atau terima kuemu saat hari H.</li></ol></aside></div></div></>;
}
export function LocationPage() { const { orderType, setOrderType } = useBakery(); return <><PageIntro label="CARI DAPUR KAMI" title="Dekat, hangat, gampang." description="Ambil sendiri atau kami antar ke sekitar dapur. Supaya yang sampai di tanganmu tetap fresh."/><div className="container page-content location-layout"><div className="location-art"><MapPin size={46} strokeWidth={1.4}/><span className="eyebrow">DAPUR RUMAHAN</span><strong className="display">Area Jakarta Selatan</strong><p>Alamat lengkap dibagikan saat pesanan dikonfirmasi.</p><small>Lokasi ini contoh untuk keperluan demo.</small></div><div className="location-details"><div className="detail-row"><Clock3 size={24}/><div><strong>Jam pesanan</strong><p>Setiap hari, 08.00–20.00<br/>Batch roti keluar oven pukul 09.00 & 15.00.</p></div></div><div className="detail-row"><ShoppingBag size={24}/><div><strong>Ambil sendiri</strong><p>Datang setelah pesanan dikonfirmasi dan rotinya siap. Alamat lengkap menyusul saat konfirmasi.</p></div></div><div className="detail-row"><Truck size={24}/><div><strong>Diantar ke rumah</strong><p>Pengantaran tersedia dalam radius 5 km. Ongkir dikonfirmasi sesuai alamat.</p></div></div><div className="filter-row"><Button variant={orderType === 'ambil' ? 'default' : 'outline'} onClick={() => setOrderType('ambil')}>Ambil Sendiri</Button><Button variant={orderType === 'antar' ? 'default' : 'outline'} onClick={() => setOrderType('antar')}>Antar (5 km)</Button></div><Button asChild><Link to="/menu">Pilih Roti Dulu <ArrowRight size={16}/></Link></Button></div></div></>; }
export function AboutPage() { return <><PageIntro label="KENALAN DULU, YUK" title="Dari dapur rumah, untuk rumahmu." description="FIDA'S lahir dari hal sederhana: pengin berbagi roti hangat yang rasanya seperti pulang."/><div className="container page-content story-section"><img className="story-photo" src={storyImage} alt="Roti sobek cokelat hangat di dapur rumahan" width={1600} height={1200}/><div className="story-text"><span className="eyebrow">KENAPA BATCH KECIL?</span><h2 className="display">Karena yang enak nggak perlu <em>diburu-buru.</em></h2><p>Resep nenek, mentega asli, dan tangan yang sabar. Kami memanggang dua kali sehari supaya setiap roti punya waktu untuk mengembang, matang, lalu dinikmati saat masih hangat.</p><p>Untuk kue custom, setiap desain dimulai dari obrolan. Kamu lihat mockup-nya dulu sebelum kami mulai membuat — karena momen spesial pantas dapat kue yang sesuai harapan.</p><span className="story-stamp">Hangatnya beneran, bukan filter ♡</span><div style={{ marginTop: 25 }}><Button asChild><Link to="/menu">Cicipi Menunya <ArrowRight size={16}/></Link></Button></div></div></div></>; }
export function CheckoutPage() {
 const { cart, orderType, clearCart } = useBakery(); const [done, setDone] = useState(false); const [name, setName] = useState(''); const [date, setDate] = useState(''); const [batch, setBatch] = useState('15.00'); const [error, setError] = useState('');
 const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
 function submit(e: FormEvent) { e.preventDefault(); if (!cart.length) return; if (date < todayJakarta()) { setError('Pilih tanggal hari ini atau setelahnya.'); return; } if (cart.some(item => item.custom) && date < tomorrow()) { setError('Kue custom perlu dipesan paling lambat H-1. Pilih besok atau setelahnya.'); return; } if (date === todayJakarta() && getJakartaMinutes() >= (batch === '09.00' ? 450 : 810)) { setError(`Batas pesan batch ${batch} hari ini sudah lewat. Pilih batch lain atau tanggal berikutnya.`); return; } setDone(true); clearCart(); }
 if (done) return <div className="checkout-done"><CheckCircle2 size={55}/><h1 className="display">Makasih, {name}!</h1><p>Simulasi pesananmu berhasil. Di toko sungguhan, kami akan mengonfirmasi pesanan, ketersediaan batch, ongkir, dan detail pembayaran sebelum mulai memanggang.</p><Button asChild><Link to="/">Kembali ke Beranda <ArrowRight size={16}/></Link></Button></div>;
 return <><PageIntro label="SATU LANGKAH LAGI" title="Siap dibikin hangat?" description="Isi detail pesananmu. Ini demo saja, jadi tidak ada pembayaran atau pesanan sungguhan yang terkirim."/><div className="container page-content cart-layout"><div>{cart.length ? <form className="custom-form" onSubmit={submit}><h2>Detail pemesan</h2><div className="form-grid"><label className="form-field">Nama lengkap<input required value={name} onChange={e => setName(e.target.value)} placeholder="Nama kamu"/></label><label className="form-field">Nomor WhatsApp<input required type="tel" pattern="[0-9+ ]{9,16}" placeholder="08xxxxxxxxxx"/></label><label className="form-field">Tanggal pesanan<input required type="date" min={cart.some(item => item.custom) ? tomorrow() : todayJakarta()} value={date} onChange={e => setDate(e.target.value)}/></label><label className="form-field">Batch roti<select value={batch} onChange={e => setBatch(e.target.value)}><option value="09.00">Pagi · 09.00 (pesan sebelum 07.30)</option><option value="15.00">Sore · 15.00 (pesan sebelum 13.30)</option></select></label>{orderType === 'antar' && <label className="form-field full">Alamat pengantaran (maks. 5 km)<textarea placeholder="Alamat lengkap dan patokan lokasi" required/></label>}<label className="form-field full">Catatan tambahan<textarea placeholder="Ada yang mau disampaikan?"/></label></div><p className="form-hint">Ketersediaan batch dan pesanan kue custom H-1 akan dikonfirmasi manual. Tidak ada pembayaran pada demo ini.</p>{error && <p role="alert" className="form-success">{error}</p>}<Button type="submit" size="lg">Simulasikan Pesanan <ArrowRight size={16}/></Button></form> : <div className="empty-state"><ShoppingBag size={36}/><h2>Belum ada pesanan.</h2><p>Pilih dulu yang kamu suka dari menu kami.</p><Button asChild><Link to="/menu">Lihat Menu</Link></Button></div>}</div>{cart.length > 0 && <div className="summary"><h2>Pesananmu</h2>{cart.map((item,index) => <div className="summary-line" key={`${item.id}-${index}`}><span>{item.quantity}× {item.name}</span><strong>{rupiah(item.price * item.quantity)}</strong></div>)}<div className="summary-line total"><span>Total sementara</span><span>{rupiah(subtotal)}</span></div><p className="summary-note">{orderType === 'ambil' ? 'Ambil sendiri' : 'Antar dalam radius 5 km'} · Ongkir, jika ada, dikonfirmasi kemudian.</p><p className="summary-note">Pesan roti sebelum 07.30 untuk batch pagi atau 13.30 untuk batch sore.</p></div>}</div></>;
}
