import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Clock3, Heart, Minus, Plus, ShoppingBag, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useBakery } from '@/components/bakery-shell';
import { CAKE_PRICES, DELIVERY_FEE, DELIVERY_MINIMUM, cakes, getNextBreadBatch, products, rupiah, type Product } from '@/lib/bakery';
import heroImage from '@/assets/hero-bread.jpg';
import storyImage from '@/assets/bread-3.jpg';

export function OvenSchedule() {
 const [next, setNext] = useState<ReturnType<typeof getNextBreadBatch> | null>(null);
 // Time is read after hydration to avoid server/client timezone mismatches.
 useEffect(() => { setNext(getNextBreadBatch()); const timer = setInterval(() => setNext(getNextBreadBatch()), 60000); return () => clearInterval(timer); }, []);
 const today = next ? new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()) : '';
 return <section className="oven-section"><div className="container oven-grid"><div className="oven-label"><span className="oven-label-icon"><Clock3 size={25}/></span><div><span className="eyebrow">SETIAP HARI</span><h2>Jadwal Keluar Oven</h2><span className="oven-status">{next ? `Pesan sekarang: ${next.date === today ? 'hari ini' : 'besok'} ${next.time}` : 'Memuat jadwal'}</span></div></div><div className="oven-slot"><div><strong>Batch Pagi</strong><p>Siap diambil 09.00</p><span className="oven-status">{next?.time === '09.00' ? (next.date === today ? 'Pesanan untuk hari ini' : 'Pesanan untuk besok') : 'Berikutnya besok pagi'}</span></div><span className="oven-time">09.00</span></div><div className="oven-slot"><div><strong>Batch Sore</strong><p>Siap diambil 15.00</p><span className="oven-status">{next?.time === '15.00' ? 'Pesanan untuk sore ini' : 'Setelah pukul 09.00'}</span></div><span className="oven-time">15.00</span></div></div></section>;
}
export function ProductCard({ product }: { product: Product }) { const { addItem } = useBakery(); return <article className="product-card"><div className="product-image"><img src={product.image} alt={product.name} loading="lazy" width={700} height={700}/>{product.label && <span className="product-label">{product.label}</span>}</div><div className="product-body"><h3>{product.name}</h3><p>{product.description}</p><div className="product-bottom"><strong>{rupiah(product.price)}</strong><Button size="sm" onClick={() => addItem(product)}>+ Tambah</Button></div></div></article>; }
export function CakeCards() { return <div className="cake-grid">{cakes.map(cake => <Link to="/kue-custom" key={cake.id} className="cake-card"><img src={cake.image} alt={cake.name} loading="lazy" width={500} height={800}/><div className="cake-card-info"><h3>{cake.name}</h3><span>Kue ultah mulai {rupiah(CAKE_PRICES['16 cm'])} →</span></div></Link>)}</div>; }
export function HomePage() { return <>
 <section className="hero"><img className="hero-image" src={heroImage} alt="Roti sobek cokelat hangat dengan lelehan cokelat" width={1600} height={1200}/><div className="container hero-content"><span className="eyebrow">DARI DAPUR KECIL KAMI, BUAT KAMU</span><h1 className="display">Masih <em>anget</em> pas sampe rumah lu.</h1><p>Batch kecil, keluar oven 09.00 & 15.00. Pesan lewat 09.00 untuk sore, lewat 15.00 untuk besok pagi.</p><div className="hero-actions"><Button asChild variant="strawberry" size="lg"><Link to="/menu">Pesan Sekarang <ArrowRight size={17}/></Link></Button><Button asChild variant="heroOutline" size="lg"><Link to="/kue-custom">Kue Custom</Link></Button></div><div className="hero-foot"><span><Sparkles size={16}/> Dipanggang tiap hari</span><span><Heart size={16}/> Mentega asli, selalu</span></div></div></section>
 <OvenSchedule/>
 <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">YANG SELALU DICARI</span><h2 className="display section-title">Favorit dari dapur kami.</h2></div><Link to="/menu" className="text-link">Lihat semua menu <ArrowRight size={17}/></Link></div><div className="products-grid">{products.slice(0, 6).map(product => <ProductCard key={product.id} product={product}/>)}</div></div></section>
 <section className="section custom-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">BUAT HARI YANG SPESIAL</span><h2 className="display section-title">Kuenya kamu, ceritanya kamu.</h2></div><Link to="/kue-custom" className="text-link">Bikin kue impianmu <ArrowRight size={17}/></Link></div><CakeCards/><p className="custom-note">✳ Pesan H-1 · DP 50% · Desain di-mockup dulu sebelum dibuat</p></div></section>
 <section className="section"><div className="container story-section"><img className="story-photo" src={storyImage} alt="Roti kayu manis hangat buatan dapur rumahan" loading="lazy" width={700} height={700}/><div className="story-text"><span className="eyebrow">CERITA DARI DAPUR</span><h2 className="display">Bukan pabrik.<br/><em>Cuma dapur rumah.</em></h2><p>Dibikin di dapur rumah, resep nenek, mentega asli — makanya batch-nya kecil. Setiap loyang dibuat pelan-pelan, biar pas nyampe di tangan kamu rasanya kayak baru keluar dari oven.</p><Link to="/tentang" className="text-link">Kenalan lebih dekat <ArrowRight size={17}/></Link><span className="story-stamp">Penuh cinta di tiap gigitan ♡</span></div></div></section>
 <section className="section testimonials"><div className="container"><div className="section-heading"><div><span className="eyebrow">KATA MEREKA</span><h2 className="display section-title">Satu gigitan, langsung ngerti.</h2></div></div><div className="testimonial-grid">{[{quote:'“Baru pertama kali beli roti yang masih hangat pas sampai rumah. Cokelatnya lumer banget!”',name:'Nadia, pelanggan roti sobek'},{quote:'“Kue ulang tahun anakku persis kayak desain yang disepakati. Rasanya juga nggak kemanisan.”',name:'Rani, pelanggan kue custom'},{quote:'“Sekarang tiap sore nungguin batch jam 3. Croissant-nya wangi mentega beneran.”',name:'Dimas, pelanggan setia'}].map(item => <div className="testimonial" key={item.name}><span className="stars">★★★★★</span><blockquote>{item.quote}</blockquote><cite>— {item.name}</cite></div>)}</div></div></section>
 <section className="cta-band"><div className="container cta-inner"><div><span className="eyebrow">JANGAN SAMPAI KEHABISAN</span><h2 className="display">Batch sore dipanggang 15.00. <em>Amankan sekarang.</em></h2></div><Button asChild variant="cream" size="lg"><Link to="/menu">Pesan Sekarang <ArrowRight size={18}/></Link></Button></div></section>
 </>; }
export function PageIntro({ label, title, description }: { label: string; title: string; description: string }) { return <div className="container page-intro"><span className="eyebrow">{label}</span><h1 className="display">{title}</h1><p>{description}</p></div>; }
export function MenuPage() { const [filter, setFilter] = useState('Semua'); const shown = filter === 'Semua' ? products : products.filter(p => p.category === filter); return <><PageIntro label="DARI OVEN KAMI" title="Pilih yang bikin ngiler." description="Roti harian dan dessert rumahan. Lewat 09.00 roti siap sore; lewat 15.00 siap besok pagi."/><OvenSchedule/><div className="container page-content menu-content"><div className="filter-row">{['Semua','Roti Harian','Dessert'].map(item => <Button key={item} variant={filter === item ? 'default' : 'outline'} onClick={() => setFilter(item)}>{item}</Button>)}</div><div className="products-grid">{shown.map(product => <ProductCard key={product.id} product={product}/>)}</div></div></>; }
export function CartPage() { const { cart, changeQuantity, orderType } = useBakery(); const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const fee = orderType === 'antar' ? DELIVERY_FEE : 0; const belowMinimum = orderType === 'antar' && subtotal < DELIVERY_MINIMUM; return <><PageIntro label="PESANAN KAMU" title="Keranjang hangatmu." description="Cek lagi semuanya sebelum kami mulai menyiapkan pesananmu."/><div className="container page-content cart-layout"><div>{cart.length ? cart.map((item,index) => <div className="cart-item" key={`${item.id}-${index}`}><img src={item.image} alt={item.name} width={110} height={100}/><div className="cart-item-main"><h3>{item.name}</h3>{item.note && <p>{item.note}</p>}<strong>{rupiah(item.price)}</strong></div><div className="quantity-control"><Button variant="icon" size="icon" aria-label={`Kurangi ${item.name}`} onClick={() => changeQuantity(item.id,-1)}><Minus size={15}/></Button><span>{item.quantity}</span><Button variant="icon" size="icon" aria-label={`Tambah ${item.name}`} onClick={() => changeQuantity(item.id,1)}><Plus size={15}/></Button></div></div>) : <div className="empty-state"><ShoppingBag size={36}/><h2>Masih kosong, nih.</h2><p>Yuk pilih yang hangat-hangat dari dapur kami.</p><Button asChild><Link to="/menu">Lihat Menu <ArrowRight size={16}/></Link></Button></div>}</div>{cart.length > 0 && <div className="summary"><h2>Ringkasan Pesanan</h2><div className="summary-line"><span>Subtotal</span><strong>{rupiah(subtotal)}</strong></div><div className="summary-line"><span>Pengambilan</span><strong>{orderType === 'ambil' ? 'Ambil sendiri' : 'Antar (maks. 5 km)'}</strong></div>{orderType === 'antar' && <div className="summary-line"><span>Ongkir tetap</span><strong>{rupiah(fee)}</strong></div>}<div className="summary-line total"><span>Total sementara</span><span>{rupiah(subtotal + fee)}</span></div>{belowMinimum && <p className="form-success" role="alert">Minimal belanja {rupiah(DELIVERY_MINIMUM)} untuk diantar. Tambah {rupiah(DELIVERY_MINIMUM - subtotal)} lagi, ya.</p>}<p className="summary-note">{cart.some(item => item.custom) ? 'Kue custom: DP 50% via WhatsApp setelah mockup disetujui. ' : ''}Ini hanya simulasi pesanan.</p><Button asChild className="w-full mt-3" size="lg"><Link to="/checkout">Lanjut ke Konfirmasi <ArrowRight size={16}/></Link></Button></div>}</div></>; }
