/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KueCustomRouteImport } from './routes/kue-custom'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as TentangRouteImport } from './routes/tentang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KueCustomRoute = KueCustomRouteImport.update({
  id: '/kue-custom',
  path: '/kue-custom',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/kue-custom': typeof KueCustomRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/kue-custom': typeof KueCustomRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/kue-custom': typeof KueCustomRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/tentang': typeof TentangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/kue-custom'
    | '/lokasi'
    | '/menu'
    | '/tentang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/kue-custom'
    | '/lokasi'
    | '/menu'
    | '/tentang'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/kue-custom'
    | '/lokasi'
    | '/menu'
    | '/tentang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  KeranjangRoute: typeof KeranjangRoute
  KueCustomRoute: typeof KueCustomRoute
  LokasiRoute: typeof LokasiRoute
  MenuRoute: typeof MenuRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kue-custom': {
      id: '/kue-custom'
      path: '/kue-custom'
      fullPath: '/kue-custom'
      preLoaderRoute: typeof KueCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  KeranjangRoute: KeranjangRoute,
  KueCustomRoute: KueCustomRoute,
  LokasiRoute: LokasiRoute,
  MenuRoute: MenuRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
